services:
  - type: web
    name: n8n
    env: docker
    region: oregon  # Optional: you can change it to a different region if needed
    plan: free      # Set to 'free' to ensure you're using the free tier
    branch: main    # Use the branch that has your render.yaml file, typically 'main'
    numInstances: 1  # Number of instances (1 is enough for the free tier)
    healthCheckPath: /  # Health check path to monitor your service
    envVars:
      - key: PGHOST
        fromDatabase:
          name: n8nDB
          property: host  # Host for the PostgreSQL database
      - key: PGDATABASE
        fromDatabase:
          name: n8nDB
          property: database  # Database name
      - key: PGPORT
        fromDatabase:
          name: n8nDB
          property: port  # Port for the PostgreSQL database
      - key: PGUSER
        fromDatabase:
          name: n8nDB
          property: user  # User for the PostgreSQL database
      - key: PGPASSWORD
        fromDatabase:
          name: n8nDB
          property: password  # Password for the PostgreSQL database

databases:
  - name: n8nDB
    plan: free   # Use the free PostgreSQL plan for the database
    ipAllowList: []  # Optional: allow access from all services
