services:
  - type: web
    name: n8n
    env: docker
    region: oregon  # Optional: you can change it
    plan: free      # ✅ Set to 'free' to avoid payment
    branch: main    # Change if your repo uses a different branch
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: PGHOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: PGPORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: PGUSER
        fromDatabase:
          name: n8nDB
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: n8nDB
          property: password
    disk:
      name: n8nDisk
      mountPath: /home/node/.n8n
      sizeGB: 1  # ✅ Keep this at 1GB or less for free plan

databases:
  - name: n8nDB
    plan: free   # ✅ Free PostgreSQL plan
    ipAllowList: []  # Optional: allow access from all services
